### ISSUE TITLE
Please show the differences between Python2 and Python3 AND Qt4 and Qt5 

### ISSUE THREAD

**Issue by RomanVolak** [goldsborough/Writer-Tutorial#4]
Is it possible to show the differences between Py3Qt5 and Py2Qt4? It's a good example but i need little bit more info.

Thanks a lot
Roman

**Comment by goldsborough** [comment]
I wrote this with Python3 and Qt4 so I can guarantee that that setup works. If you have any problems with Python3 + Qt5 or Python2 + Qt4/5 it'd be easier to open those as issues and we can just tackle those problems directly.

If you want it to work with Python2 and it doesn't out of the box, you may want to give [python-future](https://github.com/PythonCharmers/python-future) a try (untested).
