### ISSUE TITLE
help

### ISSUE THREAD

**Issue by frozenyeti789** [goldsborough/Writer-Tutorial#7]
Hey I'm completely new to gui development and coding in general. I don't know how to start or where to execute this code(yeah, dumb i know...) Aside from this, i do not know how to convert ui files to py. I really hope you'll help me out.

**Comment by goldsborough** [comment]
Have you read my [tutorials for the project](https://github.com/goldsborough/Writer-Tutorial/blob/master/README.md)? If you're new to PyQt, I remember [this tutorial](http://zetcode.com/gui/pyqt5/) was good. But if you don't know how to execute Python files you might better first do a tutorial on Python online to cover the basics. I've never really used UI files, I always programmed the GUI myself, so I can't help you with that. But [the internet is a pretty big place with lots of info](http://lmgtfy.com/?q=pyqt+ui+to+py) :blush:

**Comment by frozenyeti789** [comment]
Thank you very much for your help.

On Wed, Feb 3, 2016 at 5:59 AM, Peter Goldsborough <notifications@github.com
